#index:
#    path: /
#    controller: App\Controller\DefaultController::index

get_container:
  path: /container
  controller: App\Controller\ContainerController::getAllContainer
  methods: GET

get_containerId:
  path: /container/{id}
  controller: App\Controller\ContainerController::getContainerById
  methods: GET

get_containership:
  path: /containerShip
  controller: App\Controller\ContainerShipController::getAllContainerShip
  methods: GET

get_containershipId:
  path: /containerShip/{id}
  controller: App\Controller\ContainerShipController::getContainerShipById
  methods: GET

get_product:
  path: /product
  controller: App\Controller\ProductController::getAllProduct
  methods: GET

get_productId:
  path: /product/{id}
  controller: App\Controller\ProductController::getProductById
  methods: GET